name: Build & Deploy to Podman (Local Mac)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show workspace
        run: |
          pwd
          ls -lsa

      - name: Build image with Podman
        run: |
          podman build -t demo-podman-app:latest .

      - name: Stop and remove old container (if exists)
        run: |
          podman stop demo-podman-app || true
          podman rm demo-podman-app || true

      - name: Run container
        run: |
          podman run -d \
            --name demo-podman-app \
            -p 8080:8080 \
            demo-podman-app:latest

      - name: Show running containers
        run: podman ps
``